/**
 * HTTP client for the btcrecharge.com backend.
 *
 * The bot is a thin proxy in front of btcrecharge's existing payment +
 * fulfilment pipeline (see Decision #3 + the runbook). Every order
 * flows through:
 *
 *   POST /internal/lightning-orders  (added in Phase 2.4)
 *
 * The endpoint:
 *   - HMAC-authenticates the request with `NOSTR_PROXY_SECRET`
 *     (separate from the ppay `PROXY_SECRET` per P3, so leaking one
 *     does not compromise the other)
 *   - Validates inputs (operator slug, E.164 phone, value, callback)
 *   - Mints a fresh BTCPay invoice on the btcrecharge shared store
 *   - Returns the BOLT11 string + sats amount + expiry to the bot,
 *     which forwards them to the customer over Nostr
 *   - On BTCPay invoice settled, the existing pipeline dispatches
 *     Bitrefill + POSTs the bot's callback URL with state updates
 *
 * This client only knows about wire format and signing. The render of
 * the BOLT11 into a Nostr DM lands in Phase 2.2 / 2.3.
 */
import { createHmac, randomUUID } from 'node:crypto';
import type { Logger } from 'pino';
import { z } from 'zod';

// ----- wire types ----------------------------------------------------

export const CreateLightningOrderInputSchema = z.object({
    /** Idempotency key. UUIDv4 generated by the bot. */
    nostrOrderId:  z.string().min(8).max(64).regex(/^[A-Za-z0-9_.-]+$/),
    /** Bitrefill product slug, e.g. "airtel-india". */
    operatorSlug:  z.string().regex(/^[a-z0-9._-]{1,80}$/i),
    /** Recipient phone in E.164. */
    msisdn:        z.string().regex(/^\+[0-9]{4,18}$/),
    /** Top-up amount as the string the operator expects, e.g. "5". */
    topupValue:    z.string().min(1).max(30),
    /** Where btcrecharge POSTs state updates back to the bot. */
    callbackUrl:   z.string().url(),
    /** Customer pubkey (hex). Stored on the order for support traceability. */
    customerPubkey: z.string().regex(/^[0-9a-f]{64}$/i),
});

export type CreateLightningOrderInput = z.infer<typeof CreateLightningOrderInputSchema>;

export const CreateLightningOrderResponseSchema = z.object({
    internalOrderId: z.number().int().positive(),
    lnInvoice:       z.string().regex(/^lnbc/i, 'expected a BOLT11 starting with lnbc'),
    sats:            z.number().int().positive(),
    expiresAt:       z.number().int().positive(),
    state:           z.string(),
    idempotent:      z.boolean(),
});

export type CreateLightningOrderResponse = z.infer<typeof CreateLightningOrderResponseSchema>;

// ----- refund address (Phase 3) -------------------------------------

export const SubmitRefundAddressInputSchema = z.object({
    internalOrderId: z.number().int().positive(),
    /**
     * Lightning address (LUD-16, e.g. `alice@walletofsatoshi.com`) OR
     * LNURL-pay bech32 (`lnurl1...`). The backend probes the resolved
     * well-known endpoint before triggering the pull-payment, so an
     * unreachable address is rejected with a typed code here instead
     * of stranding the refund.
     */
    address:         z.string().min(4).max(2048),
});

export type SubmitRefundAddressInput = z.infer<typeof SubmitRefundAddressInputSchema>;

export const SubmitRefundAddressResponseSchema = z.object({
    ok:        z.literal(true),
    state:     z.string(),
});

export type SubmitRefundAddressResponse = z.infer<typeof SubmitRefundAddressResponseSchema>;

// ----- error type ----------------------------------------------------

export class BtcrechargeApiError extends Error {
    constructor(
        public readonly status: number,
        public readonly code:   string,
        message: string,
    ) {
        super(message);
        this.name = 'BtcrechargeApiError';
    }
}

// ----- client --------------------------------------------------------

export interface BtcrechargeClientOptions {
    baseUrl:        string;
    nostrProxySecret: string;
    /** Fetch impl. Pass a mock in tests. Defaults to global fetch. */
    fetchImpl?:     typeof fetch;
    /** Request timeout (ms). Defaults to 30s. */
    timeoutMs?:     number;
}

export class BtcrechargeClient {
    private readonly baseUrl:   string;
    private readonly secret:    string;
    private readonly fetchImpl: typeof fetch;
    private readonly timeoutMs: number;
    private readonly log:       Logger;

    constructor(opts: BtcrechargeClientOptions, logger: Logger) {
        this.baseUrl   = opts.baseUrl.replace(/\/$/, '');
        this.secret    = opts.nostrProxySecret;
        this.fetchImpl = opts.fetchImpl ?? fetch;
        this.timeoutMs = opts.timeoutMs ?? 30_000;
        this.log       = logger.child({ component: 'btcrecharge-client' });
    }

    /**
     * Create a Lightning-paid order. Returns the BOLT11 string the bot
     * forwards to the customer. Throws `BtcrechargeApiError` on any
     * non-2xx response so the caller can react to 409 (out of stock /
     * package not found) differently than 5xx (transient backend).
     */
    async createLightningOrder(input: CreateLightningOrderInput): Promise<CreateLightningOrderResponse> {
        const validated = CreateLightningOrderInputSchema.parse(input);
        const body = JSON.stringify({
            nostr_order_id:  validated.nostrOrderId,
            operator_slug:   validated.operatorSlug,
            msisdn:          validated.msisdn,
            topup_value:     validated.topupValue,
            callback_url:    validated.callbackUrl,
            customer_pubkey: validated.customerPubkey,
        });
        const timestamp = Math.floor(Date.now() / 1000).toString();
        const signature = this.sign(timestamp, body);

        const res = await this.postWithTimeout('/internal/lightning-orders', body, {
            'Content-Type':  'application/json',
            'X-Timestamp':   timestamp,
            'X-Signature':   signature,
            'X-Client':      'nostr',
        });

        return parseResponse(res, this.log);
    }

    /** Generate the idempotency key the bot should pass on createLightningOrder. */
    static newOrderId(): string {
        return 'nostr-' + randomUUID();
    }

    /**
     * Submit a Lightning address / LNURL for an order in `refund_pending`.
     * Backend probes the well-known/lnurlp endpoint, then triggers the
     * BTCPay pull-payment + transitions to `refunded`. Throws
     * `BtcrechargeApiError` on 4xx (typed code from the response body)
     * or 5xx so the caller can map probe-failure vs backend-down vs
     * already-refunded into distinct customer messages.
     */
    async submitRefundAddress(input: SubmitRefundAddressInput): Promise<SubmitRefundAddressResponse> {
        const validated = SubmitRefundAddressInputSchema.parse(input);
        const body = JSON.stringify({
            internal_order_id: validated.internalOrderId,
            address:           validated.address,
        });
        const timestamp = Math.floor(Date.now() / 1000).toString();
        const signature = this.sign(timestamp, body);

        const res = await this.postWithTimeout('/internal/refund-address', body, {
            'Content-Type': 'application/json',
            'X-Timestamp':  timestamp,
            'X-Signature':  signature,
            'X-Client':     'nostr',
        });

        return parseRefundResponse(res, this.log);
    }

    // ----- internals --------------------------------------------------

    /**
     * HMAC-SHA256 over `${timestamp}\n${body}` as agreed in P3. The
     * timestamp goes first so the verifier can fail fast on a stale
     * replay window without parsing the body.
     */
    private sign(timestamp: string, body: string): string {
        return createHmac('sha256', this.secret)
            .update(timestamp + '\n' + body)
            .digest('hex');
    }

    private async postWithTimeout(
        path: string,
        body: string,
        headers: Record<string, string>,
    ): Promise<Response> {
        const ctrl = new AbortController();
        const timer = setTimeout(() => ctrl.abort(), this.timeoutMs);
        try {
            return await this.fetchImpl(this.baseUrl + path, {
                method: 'POST',
                headers,
                body,
                signal: ctrl.signal,
            });
        } finally {
            clearTimeout(timer);
        }
    }
}

async function parseResponse(
    res: Response,
    log: Logger,
): Promise<CreateLightningOrderResponse> {
    const text = await res.text();
    let json: unknown;
    try { json = JSON.parse(text); }
    catch {
        log.error({ status: res.status, snippet: text.slice(0, 200) }, 'non-JSON response');
        throw new BtcrechargeApiError(res.status, 'invalid_response', 'non-JSON response from btcrecharge');
    }
    if (!res.ok) {
        const code    = (typeof json === 'object' && json !== null && 'error'  in json) ? String((json as { error: unknown }).error)  : 'unknown';
        const detail  = (typeof json === 'object' && json !== null && 'detail' in json) ? String((json as { detail: unknown }).detail) : '';
        const message = detail || code;
        log.warn({ status: res.status, code }, 'btcrecharge non-2xx');
        throw new BtcrechargeApiError(res.status, code, message);
    }
    return CreateLightningOrderResponseSchema.parse(json);
}

/**
 * Mirror of `parseResponse` but for the refund endpoint. The response
 * schema differs (no BOLT11, no sats), and the typical error codes the
 * caller cares about are `unreachable_address`, `bad_address`,
 * `order_not_refundable`. They surface through `BtcrechargeApiError.code`
 * unchanged so render.ts can map them into customer-readable messages.
 */
async function parseRefundResponse(
    res: Response,
    log: Logger,
): Promise<SubmitRefundAddressResponse> {
    const text = await res.text();
    let json: unknown;
    try { json = JSON.parse(text); }
    catch {
        log.error({ status: res.status, snippet: text.slice(0, 200) }, 'non-JSON refund response');
        throw new BtcrechargeApiError(res.status, 'invalid_response', 'non-JSON response from btcrecharge');
    }
    if (!res.ok) {
        const code    = (typeof json === 'object' && json !== null && 'error'  in json) ? String((json as { error: unknown }).error)  : 'unknown';
        const detail  = (typeof json === 'object' && json !== null && 'detail' in json) ? String((json as { detail: unknown }).detail) : '';
        const message = detail || code;
        log.warn({ status: res.status, code }, 'btcrecharge refund non-2xx');
        throw new BtcrechargeApiError(res.status, code, message);
    }
    return SubmitRefundAddressResponseSchema.parse(json);
}
